-- Seed: TK (admin) + Luca the dog
-- Generated by scripts/seed-tk-luca.mjs — safe to re-run (INSERT OR IGNORE)
INSERT OR IGNORE INTO users (openId, email, name, passwordHash, loginMethod, role, createdAt, updatedAt, lastSignedIn)
VALUES ('702bbc115445299512c371510df897f1', 'tripetkk@gmail.com', 'TK', 'pbkdf2$100000$346d2f901e62b2581f3e69b0cea0ae22$dc0ed96ea48486359b04846e45b67e99ead28cdf4286e16bbd5b6ad75b5e02c7', 'email', 'admin', unixepoch(), unixepoch(), unixepoch());

INSERT OR IGNORE INTO pets (userId, name, breed, birthDate, photoUrl, gender, createdAt, updatedAt)
SELECT id, 'Luca', NULL, NULL, NULL, 'unknown', unixepoch(), unixepoch()
FROM users WHERE email = 'tripetkk@gmail.com'
AND NOT EXISTS (SELECT 1 FROM pets WHERE name = 'Luca' AND userId = users.id);

INSERT OR IGNORE INTO feeding_schedules (petId, foodType, amount, frequency, time, notes, createdAt, updatedAt)
SELECT id, 'standard', '', 'daily', '18:00', 'Luca dinner time — historical TTS automation fired at 18:00 daily', unixepoch(), unixepoch()
FROM pets WHERE name = 'Luca'
AND NOT EXISTS (SELECT 1 FROM feeding_schedules WHERE petId = pets.id);
