/**
 * Seed TK as user + Luca as pet into the PetHealth D1 database.
 * Generates PBKDF2 hash using the same algorithm as server/_core/auth.ts.
 * Run: node scripts/seed-tk-luca.mjs <temp-password>
 * Output: drizzle/seed_tk_luca.sql (applied by deploy.sh after schema)
 */
import { webcrypto as crypto } from "node:crypto";
import { writeFileSync } from "node:fs";

const password = process.argv[2];
if (!password) {
  console.error("Usage: node scripts/seed-tk-luca.mjs <temp-password>");
  process.exit(1);
}

const encoder = new TextEncoder();

async function hashPassword(pw) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    encoder.encode(pw),
    "PBKDF2",
    false,
    ["deriveBits"]
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations: 100000, hash: "SHA-256" },
    keyMaterial,
    256
  );
  const toHex = (arr) => Array.from(arr).map(b => b.toString(16).padStart(2, "0")).join("");
  return `pbkdf2$100000$${toHex(salt)}$${toHex(new Uint8Array(bits))}`;
}

async function generateOpenId() {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  return Array.from(bytes).map(b => b.toString(16).padStart(2, "0")).join("");
}

const hash = await hashPassword(password);
const openId = await generateOpenId();

// Known Luca facts from the Obsidian vault (06-Knowledge retrospectives + tk-knowledge-hub):
// - Nickname "หมามึน", has own FB page (518759411320762)
// - 18:00 daily dinner (TTS automation existed)
const sql = `-- Seed: TK (admin) + Luca the dog
-- Generated by scripts/seed-tk-luca.mjs — safe to re-run (INSERT OR IGNORE)
INSERT OR IGNORE INTO users (openId, email, name, passwordHash, loginMethod, role, createdAt, updatedAt, lastSignedIn)
VALUES ('${openId}', 'tripetkk@gmail.com', 'TK', '${hash}', 'email', 'admin', unixepoch(), unixepoch(), unixepoch());

INSERT OR IGNORE INTO pets (userId, name, breed, birthDate, photoUrl, gender, createdAt, updatedAt)
SELECT id, 'Luca', NULL, NULL, NULL, 'unknown', unixepoch(), unixepoch()
FROM users WHERE email = 'tripetkk@gmail.com'
AND NOT EXISTS (SELECT 1 FROM pets WHERE name = 'Luca' AND userId = users.id);

INSERT OR IGNORE INTO feeding_schedules (petId, foodType, amount, frequency, time, notes, createdAt, updatedAt)
SELECT id, 'standard', '', 'daily', '18:00', 'Luca dinner time — historical TTS automation fired at 18:00 daily', unixepoch(), unixepoch()
FROM pets WHERE name = 'Luca'
AND NOT EXISTS (SELECT 1 FROM feeding_schedules WHERE petId = pets.id);
`;

writeFileSync("drizzle/seed_tk_luca.sql", sql);
console.log("✅ Seed written to drizzle/seed_tk_luca.sql");
console.log(`   User: TK <tripetkk@gmail.com> (admin, openId ${openId.slice(0, 8)}…)`);
console.log("   Pet:  Luca (dog, dinner 18:00 feeding schedule)");
